# Generated by Django 5.0.2 on 2024-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Superuser'), (2, 'Преподаватель'), (3, 'Ученик')], verbose_name='Роль'),
        ),
    ]
